### ISSUE TITLE
The Quality is so bad

### ISSUE THREAD

**Issue by mohkoma** [danielkorg/danielkorg.github.io#1] opened 2018-08-06 22:30 UTC
Hello!

Great job and good idea! I've been trying to reach the quality that you get in the demo but it seems that it's impossible, I tried almost all the parameters and I've read the "GUIDE.txt" but the vocals and the music always in the music preview except some low bass in the vocal preview!
could you please guide me how to do it right?
and the last question is this app separate just the center channel of the track?

Thank you in advance.

here is my Terminal :

```
~/Downloads/dva$ ./run_DVA.sh /usr/local/MATLAB/MATLAB_Runtime/v94
------------------------------------------
Setting up environment variables
---
LD_LIBRARY_PATH is .:/usr/local/MATLAB/MATLAB_Runtime/v94/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v94/bin/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v94/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v94/sys/opengl/lib/glnxa64
ALSA lib pcm_dsnoop.c:606:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
Error while evaluating TimerFcn for timer 'timer-1' 

Invalid or deleted object.
Error while evaluating TimerFcn for timer 'timer-2' 

Invalid or deleted object.
```

**Comment by danielkorg** [comment] 2018-08-07 21:51
Hey, 

not sure what you mean by "trying to reach the quality that you get in the demo". What demo? I will eventually post some audio demos, but there is nothing there yet, so not sure what you mean. Unless you mean the default parameters from the picture? Keep in mind, not all mixtures are the same. Some require specific parameters, it is not general yet. I am planning, in the long term, to make an app that doesn't require any parameters at all, but that's a long way still.

Also, this current version has a lot of bugs that I need to take care anyway, however I personally tested on each platform (Windows, Linux, macOS) and they all work good for me, so not exactly sure what is going on. 

If you want, can you maybe upload that mixture of yours and I will see what is wrong, I will use the Linux build like you. 

In terms of separation quality by itself, this is just the first version, the quality will be improved by a lot in the next versions, so don't worry about that. But even still, this first version works VERY nicely for me, I tested with a lot of different mixtures/challenges to see how it tackles each, so it should work with yours. 

To answer your final question, this version HAS a spatial algorithm, but that can be bypassed by setting the value to 0.0. Also, next versions will either have this completely removed or I could keep it, but again, you would have to put to 0.0 if you don't want it. Anyway, will see myself how that goes.

Thank you!

**Comment by danielkorg** [comment] 2018-08-10 21:50
I will close this issue soon, I am assuming you got it working if you didn't reply.

**Comment by mohkoma** [comment] 2018-08-10 22:00
Hello !

Sorry for the delay! I think I mixed your project with other which provide
a demo.
I can see that you don't have a demo yet.
Anyway I've tried your app many times but I still have so bad quality
result.
I'm looking forward to see the result that you get so I can have a general
view how it works.

Thank you so much

**Comment by danielkorg** [comment] 2018-08-11 00:47
Yes, but if this is some problem on Linux, I would be happy to help here. However, I am not sure what the problem is unless you maybe can share your audio file with me, you can even send me the file directly by email if you don't want others to see it here. 

I am also a bit confused what you mean by the word "quality"? Does this mean the algorithm actually works but you are not getting what you wanted from it? This is because you would have to adjust the parameters, like I said, not all mixtures are the same. Even if I show a demo, that's only for that demo, so every mixture has its parameters, would be nice if you can send a sample so I can test it myself and get back to you, give you the parameters I used on it.

**Closed** 2018-08-14 14:52 UTC
